project:
  type: book

book:
  title: "CÁLCULO ACTUARIAL"
  author: "Brayan Cubides"
  repo-url: "https://github.com/bcubides-est/Actuarial"
  repo-branch: main
  favicon: logo.png
  description: "Material de cada Curso"
  url: "/Actuarial/"
  page-navigation: true        # prev/next
  sidebar:
    tools:
    - icon: globe
      href: https://bcubides-est.github.io/website/
      text: "Ir a mi web"

    - icon: download
      href: 'javascript:window.print()'
      text: "Descargar (PDF)"
    logo: logo.png
    search: true    
  image: logo.png
  
  chapters:
    - index.qmd
    - CALCULO_ACTUARIAL/Tablas-de-Mortalidad.qmd
    - CALCULO_ACTUARIAL/Taller-Mortalidad.qmd
    - CALCULO_ACTUARIAL/Amortizacion-de-Credito.qmd
    - CALCULO_ACTUARIAL/Taller-Seguros.qmd
    - CALCULO_ACTUARIAL/Funciones-Pensiones.qmd

format:
  html:
    theme:
      light: cerulean #simplex 
      dark: cyborg
    css: custom.css
    code-fold: false
    toc-collapse: true  # Listas desplegables contraídas por defecto
    toc-depth: 1
    execute:
      output-dir: _book
    self-contained: false