project:
  type: book

book:
  title: "MATERIAL DE PREGRADO"
  author: "Brayan Cubides"
  repo-url: "https://github.com/bcubides-est/book_asignaturas"
  repo-branch: main
  favicon: logo.png
  description: "Material de cada Curso"
  url: "/book_asignaturas/"
  page-navigation: true        # prev/next
  sidebar:
    tools:
    - icon: globe
      href: https://bcubides-est.github.io/website/
      text: "Ir a mi web"

    - icon: download
      href: 'javascript:window.print()'
      text: "Descargar (PDF)"
    logo: logo.png
    search: true    
  image: logo.png
  
  chapters:
    - index.qmd
    - part: "ACTUARIAL"
      link: CALCULO_ACTUARIAL/index.qmd
      chapters:
        - CALCULO_ACTUARIAL/Tablas-de-Mortalidad.qmd
        - CALCULO_ACTUARIAL/Taller-Mortalidad.qmd
        - CALCULO_ACTUARIAL/Amortizacion-de-Credito.qmd
        - CALCULO_ACTUARIAL/Taller-Seguros.qmd
        - CALCULO_ACTUARIAL/Funciones-Pensiones.qmd

    - part: "SERIES DE TIEMPO"
      link: SERIES_DE_TIEMPO/index.qmd
      chapters:
        - SERIES_DE_TIEMPO/P0_Repaso_y_Graf_ST_Quarto.qmd
        - SERIES_DE_TIEMPO/P1_ACF_muestral_Quarto.qmd
        - SERIES_DE_TIEMPO/P1_others_Quarto.qmd
        - SERIES_DE_TIEMPO/Tarea_1_ACF_Quarto.qmd
        - SERIES_DE_TIEMPO/P2_ACF_PACF_para_AR_y_MA_Quarto.qmd
        - SERIES_DE_TIEMPO/P3_ARMA_estacionariedad_Quarto.qmd
        - SERIES_DE_TIEMPO/P4_ARMA_Box_Jenkins_Quarto.qmd
        - SERIES_DE_TIEMPO/P5_MEE_FK_Quarto.qmd
        - SERIES_DE_TIEMPO/P6_SARIMA_Quarto.qmd
        - SERIES_DE_TIEMPO/P7_Ajuste_modelos_SARIMA_Quarto.qmd
        - SERIES_DE_TIEMPO/P8_Intervencion_Quarto.qmd
        - SERIES_DE_TIEMPO/P9_Outliers_Quarto.qmd

format:
  html:
    theme:
      light: cerulean #simplex 
      dark: cyborg
    css: custom.css
    code-fold: false
    toc-collapse: true  # Listas desplegables contraídas por defecto
    toc-depth: 1
    execute:
      output-dir: _book
    self-contained: false