project:
  type: book

book:
  title: "MATERIAL DE PREGRADO"
  author: "Brayan Cubides"
  repo-url: "https://github.com/bcubides-est/actuarial"
  repo-branch: main
  favicon: logo.png
  description: "Material de cada Curso"
  url: "/book_asignaturas/"
  page-navigation: true        # prev/next
  sidebar:
    tools:
    - icon: globe
      href: https://bcubides-est.github.io/website/
      text: "Ir a mi web"

    - icon: download
      href: 'javascript:window.print()'
      text: "Descargar (PDF)"
    logo: logo.png
    search: true               # buscador
  #repo-actions: [edit, issue, source]
  #sharing: [twitter, linkedin, facebook]  # botones de compartir
  #downloads: [pdf]             # botón de descarga PDF
  image: logo.png
  
  chapters:
    - index.qmd
    - CALCULO_ACTUARIAL/index.qmd
    - CALCULO_ACTUARIAL/Corte-1-Mortalidad/Tablas-de-Mortalidad.qmd
    - CALCULO_ACTUARIAL/Corte-1-Mortalidad/Taller-Mortalidad.qmd
    - CALCULO_ACTUARIAL/Corte-2-Tablas-Amortizacion-Credito/Amortizacion-de-Credito.qmd
    - CALCULO_ACTUARIAL/Corte-3-Seguros/Taller-Seguros.qmd
    - CALCULO_ACTUARIAL/Corte-4-Pensiones/Funciones-Pensiones.qmd
    - SERIES_DE_TIEMPO/index.qmd

format:
  html:
    theme:
      light: cerulean #simplex 
      dark: cyborg
    css: custom.css
    code-fold: false