project:
  type: book

book:
  title: "MATERIAL DE PREGRADO"
  author: "Brayan Cubides"
  repo-url: "https://github.com/bcubides-est/actuarial"
  repo-branch: main
  favicon: logo.png
  description: "Material de cada Curso"
  url: "/book_asignaturas/"
  page-navigation: true        # prev/next
  sidebar:
    tools:
    - icon: globe
      href: https://bcubides-est.github.io/website/
      text: "Ir a mi web"

    - icon: download
      href: 'javascript:window.print()'
      text: "Descargar (PDF)"
    logo: logo.png
    search: true    
  image: logo.png
  
  chapters:
    - index.qmd
    - part: "ACTUARIAL"
      link: CALCULO_ACTUARIAL/index.qmd
      chapters:
        - CALCULO_ACTUARIAL/Corte-1-Mortalidad/Tablas-de-Mortalidad.qmd
        - CALCULO_ACTUARIAL/Corte-1-Mortalidad/Taller-Mortalidad.qmd
        - CALCULO_ACTUARIAL/Corte-2-Tablas-Amortizacion-Credito/Amortizacion-de-Credito.qmd
        - CALCULO_ACTUARIAL/Corte-3-Seguros/Taller-Seguros.qmd
        - CALCULO_ACTUARIAL/Corte-4-Pensiones/Funciones-Pensiones.qmd
    - part: "SERIES DE TIEMPO"
      link: SERIES_DE_TIEMPO/index.qmd
      chapters:
        - SERIES_DE_TIEMPO/index.qmd

format:
  html:
    theme:
      light: cerulean #simplex 
      dark: cyborg
    css: custom.css
    code-fold: false
    toc-collapse: true  # Listas desplegables contraídas por defecto
    toc-depth: 1