project:
  type: website

website:
  title: "Mis Cursos de Pregrado"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: Perfil.qmd
        text: Perfil 
  favicon: "logo.png"

format:
  html:
    theme:
      - cosmo
    toc: false
    favicon: "logo.png"
