name: Publish Actuarial Book

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Quarto & R
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          install: ["r", "quarto"]

      - name: Render book
        run: |
          cd "9 CÁLCULO ACTUARIAL"
          quarto render

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: "9 CÁLCULO ACTUARIAL/_book"

