on:
  push:
    branches: main

name: Build & Deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2   # si usas renv
      - uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages